//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p2_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupa_tipa_proizvoda
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Grupa_tipa_proizvoda()
        {
            this.Tip_Proizvoda = new HashSet<Tip_Proizvoda>();
        }
    
        public long Grupa_tipa_proizvoda_ID { get; set; }
        public string Naziv_grupe_tipa_proizvoda { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tip_Proizvoda> Tip_Proizvoda { get; set; }
    }
}
