//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p2_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregledi
    {
        public long Pregled_ID { get; set; }
        public string Pregledac { get; set; }
        public Nullable<long> Ocjena { get; set; }
        public string Komentar { get; set; }
        public Nullable<System.DateTime> Datum_ocjenjivanja { get; set; }
        public Nullable<long> FK_Proizvod_ID { get; set; }
    
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
