//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p2_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proizvodi()
        {
            this.Pregledis = new HashSet<Pregledi>();
            this.Proizvodi_Korisnici = new HashSet<Proizvodi_Korisnici>();
        }
    
        public long Proizvod_ID { get; set; }
        public string Naziv { get; set; }
        public Nullable<double> Cijena { get; set; }
        public string Opis { get; set; }
        public string Naziv_Slike { get; set; }
        public bool Active { get; set; }
        public Nullable<long> FK_Tip_Proizvoda { get; set; }
        public bool Istaknuti { get; set; }
        public bool Akcija { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pregledi> Pregledis { get; set; }
        public virtual Tip_Proizvoda Tip_Proizvoda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proizvodi_Korisnici> Proizvodi_Korisnici { get; set; }
    }
}
