//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace p2_shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proizvodi_Korisnici
    {
        public long Kupovina_ID { get; set; }
        public Nullable<long> FK_Proizvodi { get; set; }
        public Nullable<long> FK_Korisnici { get; set; }
    
        public virtual Korisnici Korisnici { get; set; }
        public virtual Proizvodi Proizvodi { get; set; }
    }
}
